### ISSUE TITLE
Node can't find ebay_search@1.0.0

### ISSUE THREAD

**Issue by vintaclectic** [programming-is-cool/eBay-completed-listings#1]
Upon installing, everything was fine except probably one of the most important packages...ebay_search@1.0.0 was not found. Any ideas?

**Comment by programming-is-cool** [comment]
Is this an error you are receiving and if so, when?  I just cloned the repo, ran 'npm install', then ran 'npm start' and everything ran smoothly.

**Comment by programming-is-cool** [comment]
Sorry for the delayed response.

**Comment by vintaclectic** [comment]
It's just telling me ebay_search does not exist, there isn't even a repository for it it claims and i can't seem to find one either...?

**Comment by programming-is-cool** [comment]
What are you typing in to get that error message?

**Comment by vintaclectic** [comment]
literally running npm install, npm start
it installs, then i npm start, and it tells me to tell author there's nothing found for ebay_search@1.0.0

**Comment by vintaclectic** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ebay_search@1.0.0~prestart: ebay_search@1.0.0
6 silly lifecycle ebay_search@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle ebay_search@1.0.0~start: ebay_search@1.0.0
8 verbose lifecycle ebay_search@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ebay_search@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/mnt/c/Users/bmjustic/Google Drive/WEB CODING/WEBSITE PORFOLIOS/EYEOFJUSTICE/TEMPLATES/TheLeader/BETA/eBay-completed-listings/node_modules/.bin:/home/skwingar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Python38-32/Scripts:/mnt/c/Program Files (x86)/Python38-32:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/Calibre2:/mnt/c/Program Files/dotnet:/mnt/c/Users/bmjustic/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/bmjustic/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
10 verbose lifecycle ebay_search@1.0.0~start: CWD: /mnt/c/Users/bmjustic/Google Drive/WEB CODING/WEBSITE PORFOLIOS/EYEOFJUSTICE/TEMPLATES/TheLeader/BETA/eBay-completed-listings
11 silly lifecycle ebay_search@1.0.0~start: Args: [ '-c', 'webpack && electron .' ]
12 info lifecycle ebay_search@1.0.0~start: Failed to exec start script
13 verbose stack Error: ebay_search@1.0.0 start: `webpack && electron .`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ebay_search@1.0.0
15 verbose cwd /mnt/c/Users/bmjustic/Google Drive/WEB CODING/WEBSITE PORFOLIOS/EYEOFJUSTICE/TEMPLATES/TheLeader/BETA/eBay-completed-listings
16 error Linux 4.4.0-17763-Microsoft
17 error argv "/usr/bin/node" "/usr/bin/npm" "start"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error ebay_search@1.0.0 start: `webpack && electron .`
24 error spawn ENOENT
25 error Failed at the ebay_search@1.0.0 start script 'webpack && electron .'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the ebay_search package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     webpack && electron .
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs ebay_search
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls ebay_search
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by programming-is-cool** [comment]
It looks like you are running an old version of node and npm. Have you tried upgrading node?

**Comment by programming-is-cool** [comment]
When you type: 

`npm  —version`

what is returned?

**Comment by vintaclectic** [comment]
I've upgraded both, still same error. Version is 6.13.1

**Comment by programming-is-cool** [comment]
I just published a release for the app with the files packaged already.  You could download the win32-64 version (Windows) or the darwin version (Mac).  Let me know if that solves that works for you.

**Comment by vintaclectic** [comment]
I downloaded the release, extracted it and found absolutely nothing inside to open...

**Comment by programming-is-cool** [comment]
If you downloaded the Windows version, double click the "eBay Completed.exe" file.  If you downloaded the mac version, double click the "eBay Completed.app" file.

**Comment by programming-is-cool** [comment]
Did that work out for you?

**Comment by vintaclectic** [comment]
Dude, I don't know what you're trying to do but tomorrow i'll send you a screenshot when I get time to show you specifically that there is nothing executable in the release zip...

**Comment by vintaclectic** [comment]
What folder should the exe be in? I have searched every single one

**Comment by programming-is-cool** [comment]
![image](https://user-images.githubusercontent.com/39038759/76658727-1ce5db80-654b-11ea-90a2-c842224418dc.jpg)


The highlighted file in the picture is the executable. The file structure is visible on the top search bar in the picture.

**Comment by vintaclectic** [comment]
YAYY, finally got it! The problem...I was downloading the "eBay.Completed-darwin-x64.zip" archive and not the win32-x64 one for some reason. Thanks for all your patience, due diligence and help!

**Comment by vintaclectic** [comment]
One request, on next release...make each individual result clickable to ebay url
